### ISSUE TITLE
Question: is this the free service?

### ISSUE THREAD

**Issue by schtibe** [gido/postcardcreator#2]
Hi. Just a quick question: is this API working with the free postcard service, i.e. the mobile app version, or is it the online version?

**Comment by gido** [comment]
@schtibe Hi, Yes is it build to use the free edition (1 postcard per 24h by account) in mind.

Actually, I'm not sure it work out-of-the-box with the paid services.

Cheers!

**Comment by schtibe** [comment]
@gido Hi, yes after I posted the question I remembered you saying you had to wait for a day to test at the SwissJS :)
It seems that I have done a mistake and sent an order twice, which would then mean it costs, which would mean the paid service works as well. I can tell you as soon as I receive them.

**Comment by gido** [comment]
@schtibe Don't worry, it seem that the Swiss Post have a queue on their side and will just delay the delivery of your second test.

**Comment by schtibe** [comment]
Ok, I did receive the postcard twice. Also have a look at the order emails: http://www.pasteall.org/pic/show.php?id=92689 (check the time).
But, I didn't have to pay for it (yet?). No sign about any payment. So, either I was lucky or they don't really check it.. I'm more careful now any ways. In any way, thanks for the help!
