### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by BinaryBrain** [gido/postcardcreator#5]
Hi,
How do you add line breaks in your postcard text?
Awesome hack, by the way. Thanks!

**Comment by schtibe** [comment]
Just wanted to ask the same. I tried with \r\n, but it didn't work.

**Comment by BinaryBrain** [comment]
I still didn't try. Maybe `<br>` works. I don't know.

**Comment by schtibe** [comment]
I might have found a way, but can't try it right away. Stay tuned

**Comment by schtibe** [comment]
I'm trying it with this change: https://github.com/schtibe/postcardcreator/commit/6c58250e6118944a373f36347fc0e4b7444f2d1c

Postcard is under way, will tell you when I received it ;)

**Comment by schtibe** [comment]
No success so far :(

**Comment by BinaryBrain** [comment]
@gido Do you know how to do it? Has someone figured it out or do we have to reverse engineer it?

**Comment by schtibe** [comment]
@BinaryBrain I think I know now. I made the regex wrong, only replaced the first newline, but it seems to have actually worked.

**Comment by gido** [comment]
Fixed in #13
