### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by schtibe** [gido/postcardcreator#6]
Is this library still working even though they made some changes to the postcard creator?

**Comment by gido** [comment]
Nope :cry: 

The new authentication system is not compatible with the current one.

**Comment by eddex** [comment]
Any intentions on supporting the new API?

**Comment by schtibe** [comment]
Is it just the authentication system or the whole API that they changed?

**Comment by gido** [comment]
Can't say for now. I hope it's only the authentication system.

**Comment by gido** [comment]
Good news!
I explored a bit the changes and it looks like the new API didn't really changed. The authentication system is based on a bearer token and a is just under a new endpoint.

The bad is that the authentication token is somehow painful to get and expire after 1 hour.

**Comment by schtibe** [comment]
Nice! I looked into the authentication proces myself a bit, and indeed it does not seem to be straight forward. Maybe we can collect our knowledge somewhere?

**Comment by gido** [comment]
I started working on it on the [2.0 branch](https://github.com/gido/postcardcreator/tree/2.0).

To get a valid token I will try to reproduce these steps:

#### 1. SSO Authentication : submit credentials

```
POST /SAML/IdentityProvider/?login&app=pcc&service=pcc&targetURL=https%3A%2F%2Fpostcardcreator.post.ch&abortURL=https%3A%2F%2Fpostcardcreator.post.ch&inMobileApp=true HTTP/1.1
Host: account.post.ch
Content-Type: application/x-www-form-urlencoded
Accept-Language: en-US
Cookie: [...]
X-Requested-With: ch.post.it.pcc

isiwebuserid=[EMAIL]&isiwebpasswd=[PASSWORD]&confirmLogin=
```

_Note:_ Maybe a step 0 is required if there is a CSRF like cookie based security.

#### 2. SSO Authentication : get the SAMLResponse

```
POST /SAML/IdentityProvider/?login&app=pcc&service=pcc&targetURL=https%3A%2F%2Fpostcardcreator.post.ch&abortURL=https%3A%2F%2Fpostcardcreator.post.ch&inMobileApp=true HTTP/1.1
Host: account.post.ch
Content-Length: 0
Content-Type: application/x-www-form-urlencoded
Accept-Language: en-US
X-Requested-With: ch.post.it.pcc
Cookie: [...]
```

_Note:_ I suppose we need to handle cookies for this request...

#### 3. SSO Authentication : get the access token from postcardcreator service

```
POST /saml/SSO/alias/defaultAlias HTTP/1.1
Host: postcardcreator.post.ch
Content-Type: application/x-www-form-urlencoded
Accept-Language: en-US
X-Requested-With: ch.post.it.pcc
Cookie: [...]

RelayState=[RelayState]&SAMLResponse=[SAMLResponse]
```

_Note:_ extract `RelayState` and `SAMLResponse` values from response of step 2.

and you will get a valid token:

``` json
{
    "expires_in": "3599",
    "token_type": "bearer",
    "access_token": "here is the access token"
}
```

**Comment by gido** [comment]
2.0 release make it work again

**Comment by mr-deamon** [comment]
Is 2.0-branch still working? I receive 401-messages but did not yet investigate further (will try to do this soon-ish)

**Comment by schtibe** [comment]
@mr-deamon Yes it is working. Your error might have been solved already, check out #7 and #9

**Comment by mr-deamon** [comment]
so, stupid node-beginner-question: can't i just npm install, set the ENV-vars, enter an address/text/imagepath in the example-script and execute node sendpostcard.js? I ensured that #9 is in place...

**Comment by schtibe** [comment]
@mr-deamon I guess this should work. Do you have problems? Also check out this application, it's built on the postcardcreator library: https://github.com/schtibe/postcardy

**Comment by mr-deamon** [comment]
Yes, still a 401:
`$ node examples/sendpostcard.js 
Created a client with credentials info@xxx.ch
ERREUR:  { status: 401, message: 'Unable to complete HTTP request' }
** ERROR ** on users.current()  { status: 401, message: 'Unable to complete HTTP request' }
Error when sending the postcard.  { status: 401, message: 'Unable to complete HTTP request' }`

User/password are working with the App and the error is not ENV-related, hardcoded credentials do not help.
I'll have look into your link later, thanks!

Edit: The app in you link is working. I will try to figure out why the "pure" script is not working...

**Comment by schtibe** [comment]
How did you ensure that #9 is in place?

**Comment by mr-deamon** [comment]
At the moment by changing the file by hand... My understanding is that #7 and #9 are basically fixing the same thing, correct?

**Comment by schtibe** [comment]
@mr-deamon Ah wait... did you send a postcard and are now trying to do it again? I'm not quite sure what the error is when you try to send multiple postcards within the same 24 hrs...

**Comment by mr-deamon** [comment]
Well. yesterday i was not able to send, but today your other repo was
working, so mi last tests were after a successfull try and within the 24h
limit.

**Comment by schtibe** [comment]
If you still fail to send it via "pure" script, please show me the script and the exact steps you take

**Comment by gido** [comment]
To help you debugging about the 24h limit, you can use the [Quota API](https://github.com/gido/postcardcreator/blob/master/lib/Users.js#L27)
