### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by BinaryBrain** [gido/postcardcreator#7]
I'm not sure why, but I had to add a `.access_token` to the `Client.authToken` [on Client.js line 181](https://github.com/gido/postcardcreator/blob/master/lib/Client.js#L181) in order to get the token string and avoid a 401 error.
Maybe their API changed, but anyway it seems to work with:

```
options.headers['Authorization'] = 'Bearer ' + this.authToken.access_token;
```

**Comment by gido** [comment]
Oh!
I think the error is in the documentation or in my example.
Thanks for the report!

Happy postcarding 📮 !

**Comment by schtibe** [comment]
Yes, this solved my problem as well.

**Comment by schtibe** [comment]
Yes, this solved my problem as well. @binarybrain: will you make a pull request?

**Comment by gido** [comment]
See https://github.com/gido/postcardcreator/pull/8#issuecomment-403570785
